export const USER_LOGIN_INIT = 'USER_LOGIN_INIT';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_REGISTER_INIT = 'USER_REGISTER_INIT';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_UPDATE_INIT = 'USER_UPDATE_INIT';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const GET_COUNTRY_INIT = 'GET_COUNTRY_INIT';
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS';
export const GET_COUNTRY_FAIL = 'GET_COUNTRY_FAIL';

export const GET_CITY_INIT = 'GET_CITY_INIT';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';
export const GET_CITY_FAIL = 'GET_CITY_FAIL';
export const GET_LANGUAGE_SUCCESS = 'GET_LANGUAGE_SUCCESS';

export const GET_SINGLE_PROFILE_INIT = 'GET_SINGLE_PROFILE_INIT';
export const GET_SINGLE_PROFILE_SUCCESS = 'GET_SINGLE_PROFILE_SUCCESS';
export const GET_SINGLE_PROFILE_FAIL = 'GET_SINGLE_PROFILE_FAIL';

export const GET_LANDING_PAGE_USER_INIT = 'GET_LANDING_PAGE_USER_INIT';
export const GET_LANDING_PAGE_USER_SUCCESS = 'GET_LANDING_PAGE_USER_SUCCESS';
export const GET_LANDING_PAGE_USER_FAIL = 'GET_LANDING_PAGE_USER_FAIL';

